// GENERATED by tool/ballot/build_ballot.py — do not edit by hand.
// Edit emerge_ky_seed.json or tool/ballot/ballot_enrichment.json, then
// run `python3 tool/ballot/build_ballot.py`.

import 'package:npo_community/features/alumni_running/models/alumni_candidate.dart';

const String alumniCandidatesElection = '2026 General Election · Nov. 3, 2026';

/// Candidate cards come down once Election Day is over.
final DateTime alumniCandidatesHideAfter = DateTime(2026, 11, 4);

/// Emerge Kentucky alumnae on the Nov. 3, 2026 ballot
/// (45 confirmed in emerge_ky_seed.json).
final List<AlumniCandidate> alumniCandidates2026 = List.unmodifiable([
  AlumniCandidate(
    seedId: 'emky-megan-bailey',
    name: 'Megan Bailey',
    classYear: 2021,
    office: 'Warren County Magistrate, District 4',
    election: alumniCandidatesElection,
    status: 'vs. Rex A. McWhorter',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2021/01/Megan-Bailey_400x400_acf_cropped.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-almaria-baker',
    name: 'Almaria Baker',
    classYear: 2023,
    office: 'Kentucky House of Representatives, District 28',
    election: alumniCandidatesElection,
    status: 'vs. Jared Bauman',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2023/01/Almaria-Baker_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://www.bakerforhouse28.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Almaria_Baker'),
    donateUrl: Uri.parse('https://secure.actblue.com/donate/team-baker-1'),
    volunteerOpportunities: [
      VolunteerOpportunity(
        title: 'Walk with Dr. Almaria Baker (HD 28)',
        startsAt: DateTime(2026, 10, 3, 10, 0),
        endsAt: DateTime(2026, 10, 3, 12, 0),
        location: 'Panera Bread, 6900 Dixie Hwy, Louisville',
        signupUrl: Uri.parse(
          'https://www.mobilize.us/louisvilledemocrats/event/1001043/',
        ),
      ),
      VolunteerOpportunity(
        title: 'Walk with Dr. Almaria Baker (HD 28)',
        startsAt: DateTime(2026, 10, 10, 10, 0),
        endsAt: DateTime(2026, 10, 10, 12, 0),
        location: 'Panera Bread, 6900 Dixie Hwy, Louisville',
        signupUrl: Uri.parse(
          'https://www.mobilize.us/louisvilledemocrats/event/1001043/',
        ),
      ),
      VolunteerOpportunity(
        title: 'Walk with Dr. Almaria Baker (HD 28)',
        startsAt: DateTime(2026, 10, 17, 10, 0),
        endsAt: DateTime(2026, 10, 17, 12, 0),
        location: 'Panera Bread, 6900 Dixie Hwy, Louisville',
        signupUrl: Uri.parse(
          'https://www.mobilize.us/louisvilledemocrats/event/1001043/',
        ),
      ),
      VolunteerOpportunity(
        title: 'Walk with Dr. Almaria Baker (HD 28)',
        startsAt: DateTime(2026, 10, 24, 10, 0),
        endsAt: DateTime(2026, 10, 24, 12, 0),
        location: 'Panera Bread, 6900 Dixie Hwy, Louisville',
        signupUrl: Uri.parse(
          'https://www.mobilize.us/louisvilledemocrats/event/1001043/',
        ),
      ),
      VolunteerOpportunity(
        title: 'Walk with Dr. Almaria Baker (HD 28)',
        startsAt: DateTime(2026, 10, 31, 10, 0),
        endsAt: DateTime(2026, 10, 31, 12, 0),
        location: 'Panera Bread, 6900 Dixie Hwy, Louisville',
        signupUrl: Uri.parse(
          'https://www.mobilize.us/louisvilledemocrats/event/1001043/',
        ),
      ),
    ],
  ),
  AlumniCandidate(
    seedId: 'emky-amy-beasley',
    name: 'Amy Beasley',
    classYear: 2013,
    office: 'Lexington-Fayette Urban County Council, District 8',
    election: alumniCandidatesElection,
    status: 'Incumbent; vs. Tray Hughes',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/Amy-Beasley-Brown.jpg',
    ),
    campaignUrl: Uri.parse('https://beasleyforlex.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Amy_Beasley'),
    donateUrl: Uri.parse('https://secure.actblue.com/donate/amy-beasley-1'),
  ),
  AlumniCandidate(
    seedId: 'emky-dana-beasley-brown',
    name: 'Dana Beasley-Brown',
    classYear: 2018,
    office: 'Bowling Green City Commission, At-large',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/Daaa_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://danaforbg.com/'),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Dana_Beasley_Brown_(Bowling_Green_City_Commission_At-large,_Kentucky,_candidate_2024)',
    ),
    volunteerUrl: Uri.parse('https://forms.gle/r9J9dgj1aSz6Fwiv8'),
    donateUrl: Uri.parse('https://secure.actblue.com/donate/dana4bg'),
    volunteerOpportunities: [
      VolunteerOpportunity(
        title: 'KFTC phone bank for New Power PAC candidates, incl. Dana',
        startsAt: DateTime(2026, 10, 26, 18, 0),
        endsAt: DateTime(2026, 10, 26, 20, 0),
        location: 'Virtual (Bowling Green, Central time)',
        signupUrl: Uri.parse('https://www.mobilize.us/kftc/event/1043123/'),
      ),
      VolunteerOpportunity(
        title: 'KFTC phone bank for New Power PAC candidates, incl. Dana',
        startsAt: DateTime(2026, 10, 27, 18, 30),
        endsAt: DateTime(2026, 10, 27, 20, 0),
        location: 'Virtual (Bowling Green, Central time)',
        signupUrl: Uri.parse('https://www.mobilize.us/kftc/event/1043123/'),
      ),
    ],
  ),
  AlumniCandidate(
    seedId: 'emky-karen-berg',
    name: 'Karen Berg',
    classYear: 2017,
    office: 'Kentucky State Senate, District 26',
    election: alumniCandidatesElection,
    status: 'Incumbent; vs. Everett C. Corley',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/Screen-Shot-2018-07-03-at-2.00.10-PM_400x400_acf_cropped.png',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Karen_Berg'),
  ),
  AlumniCandidate(
    seedId: 'emky-tina-bojanowski',
    name: 'Tina Bojanowski',
    classYear: 2017,
    office: 'Kentucky House of Representatives, District 32',
    election: alumniCandidatesElection,
    status: 'Incumbent, unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/27503429_506181686434964_6116258977002893573_o_400x400_acf_cropped.jpg',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Tina_Bojanowski'),
  ),
  AlumniCandidate(
    seedId: 'emky-alison-brotzge-elder',
    name: 'Alison Brotzge-Elder',
    classYear: 2022,
    office: 'Louisville Metro Council, District 9',
    election: alumniCandidatesElection,
    status: 'Open seat; vs. Andrea Parr',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/01/Class-of-2022-Alison-Brotzge-Elder.png',
    ),
    campaignUrl: Uri.parse('https://www.alisonforlouisville.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Alison_Brotzge-Elder'),
    volunteerUrl: Uri.parse(
      'https://docs.google.com/forms/d/e/1FAIpQLSfjJ2cOVhKXpOG0rGzpO_PMsTJbkZu6e_RyYrqmMvJZYgm8kg/viewform?usp=dialog',
    ),
    donateUrl: Uri.parse(
      'https://secure.actblue.com/donate/alisonforlouisville',
    ),
    volunteerOpportunities: [
      VolunteerOpportunity(
        title: 'Talk to voters with Alison',
        startsAt: DateTime(2026, 10, 3, 10, 0),
        endsAt: DateTime(2026, 10, 3, 12, 0),
        location: 'Heine Brothers Clifton, 2309 Frankfort Ave, Louisville',
        signupUrl: Uri.parse(
          'https://www.alisonforlouisville.com/event-details/saturdays-join-alison-talking-to-voters-2026-10-03-10-00',
        ),
      ),
      VolunteerOpportunity(
        title: 'Talk to voters with Alison',
        startsAt: DateTime(2026, 10, 10, 10, 0),
        endsAt: DateTime(2026, 10, 10, 12, 0),
        location: 'Heine Brothers Clifton, 2309 Frankfort Ave, Louisville',
        signupUrl: Uri.parse(
          'https://www.alisonforlouisville.com/event-details/saturdays-join-alison-talking-to-voters-2026-10-03-10-00',
        ),
      ),
      VolunteerOpportunity(
        title: 'Talk to voters with Alison',
        startsAt: DateTime(2026, 10, 17, 10, 0),
        endsAt: DateTime(2026, 10, 17, 12, 0),
        location: 'Heine Brothers Clifton, 2309 Frankfort Ave, Louisville',
        signupUrl: Uri.parse(
          'https://www.alisonforlouisville.com/event-details/saturdays-join-alison-talking-to-voters-2026-10-03-10-00',
        ),
      ),
      VolunteerOpportunity(
        title: 'Talk to voters with Alison',
        startsAt: DateTime(2026, 10, 24, 10, 0),
        endsAt: DateTime(2026, 10, 24, 12, 0),
        location: 'Heine Brothers Clifton, 2309 Frankfort Ave, Louisville',
        signupUrl: Uri.parse(
          'https://www.alisonforlouisville.com/event-details/saturdays-join-alison-talking-to-voters-2026-10-03-10-00',
        ),
      ),
    ],
  ),
  AlumniCandidate(
    seedId: 'emky-tina-bryson',
    name: 'Tina Bryson',
    classYear: 2026,
    office: 'Lexington-Fayette Urban County Council, District 6',
    election: alumniCandidatesElection,
    status: 'Open seat; vs. Tyler M. Pyles',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2026/07/Tina-Bryson_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://www.tinabrysonforlex6.com/'),
    volunteerUrl: Uri.parse('https://www.tinabrysonforlex6.com/get-involved'),
    donateUrl: Uri.parse('https://secure.anedot.com/tbrysonlex6/givetoday'),
  ),
  AlumniCandidate(
    seedId: 'emky-josephine-buckner',
    name: 'Josephine Buckner',
    classYear: 2013,
    office: 'Jefferson District Court Judge, Division 12',
    election: alumniCandidatesElection,
    status: 'Unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/Buckner_Josephine_092121_web.jpg',
    ),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Josephine_Layne_Buckner',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-lindsey-burke',
    name: 'Lindsey Burke',
    classYear: 2020,
    office: 'Kentucky House of Representatives, District 75',
    election: alumniCandidatesElection,
    status: 'Incumbent',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/02/FB_IMG_1623197235546-Lindsey-Burke_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://lindseyburke.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Lindsey_Burke'),
    donateUrl: Uri.parse('https://secure.actblue.com/donate/lbweb'),
  ),
  AlumniCandidate(
    seedId: 'emky-chrysanthia-carr-seals',
    name: 'Chrysanthia Carr-Seals',
    classYear: 2014,
    office: 'Fayette County Magistrate, District 3',
    election: alumniCandidatesElection,
    status: 'Won Dem primary',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/Screen-Shot-2018-07-03-at-12.12.47-PM_400x400_acf_cropped.png',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Chrysanthia_Carr-Seals'),
  ),
  AlumniCandidate(
    seedId: 'emky-leticia-cline',
    name: 'Leticia Cline',
    classYear: 2020,
    office: 'Cave City Council, At-large',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2020/08/Leticia-Headshot.jpg',
    ),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Leticia_Cline_(Cave_City_City_Council_At-large,_Kentucky,_candidate_2024)',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-mera-kathryn-corlett',
    name: 'Mera Kathryn Corlett',
    classYear: 2020,
    office: 'Jefferson County Magistrate (Justice of the Peace), District 1',
    election: alumniCandidatesElection,
    status: 'Unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2020/08/Mera-Corlett.jpg',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Mera_Corlett'),
  ),
  AlumniCandidate(
    seedId: 'emky-anne-delahanty',
    name: 'Anne Delahanty',
    classYear: 2014,
    office: 'Jefferson District Court Judge, Division 13',
    election: alumniCandidatesElection,
    status: 'Unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/1655802_212082345657819_60731915_o_400x400_acf_cropped.jpg',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Anne_Delahanty'),
  ),
  AlumniCandidate(
    seedId: 'emky-yolanda-buford-demaree',
    name: 'Yolanda Buford Demaree',
    classYear: 2022,
    office: 'Langdon Place City Commission',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/01/Yolanda-Emerge-Ky-Yolanda-Demaree_400x400_acf_cropped.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-anne-gay-donworth',
    name: 'Anne Gay Donworth',
    classYear: 2023,
    office: 'Kentucky House of Representatives, District 76',
    election: alumniCandidatesElection,
    status: 'Incumbent',
    photoUrl: Uri.parse(
      'https://images.squarespace-cdn.com/content/v1/65c82a45a0fd0602278ceca4/642e0335-8b60-4c7c-b7ac-9070c75d905a/240121_Anne+Donworth_MM_0083-Edit-2.jpg?format=500w',
    ),
    campaignUrl: Uri.parse('https://www.annegaydonworth.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Anne_Donworth'),
    volunteerUrl: Uri.parse('https://www.annegaydonworth.com/volunteer'),
    donateUrl: Uri.parse('https://secure.actblue.com/donate/agdwebsite'),
  ),
  AlumniCandidate(
    seedId: 'emky-claire-estill',
    name: 'Claire Estill',
    classYear: 2019,
    office: 'Mason County Attorney',
    election: alumniCandidatesElection,
    status: 'Unopposed; filed as A. Claire Estill McHugh',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2019/01/IMG_0242-2_400x400_acf_cropped.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-angela-evans',
    name: 'Angela Evans',
    classYear: 2013,
    office: 'Fayette County Attorney',
    election: alumniCandidatesElection,
    status: 'Incumbent, unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/02/Princeton-announcement-photo-red_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://www.electangelaevans.com/'),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Angela_Evans_(Kentucky)',
    ),
    donateUrl: Uri.parse('https://secure.actblue.com/donate/eae'),
  ),
  AlumniCandidate(
    seedId: 'emky-karen-faulkner',
    name: 'Karen Faulkner',
    classYear: 2018,
    office: 'Jefferson District Court Judge, Division 8',
    election: alumniCandidatesElection,
    status: 'vs. Jonathan Max Allen',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/36281878_2183484418540230_4487986480651698176_n_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://www.votekarenfaulkner.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Karen_Faulkner'),
    volunteerUrl: Uri.parse('https://www.votekarenfaulkner.com/get-involved'),
    donateUrl: Uri.parse('https://www.votekarenfaulkner.com/donate'),
  ),
  AlumniCandidate(
    seedId: 'emky-sarah-froelich',
    name: 'Sarah Froelich',
    classYear: 2021,
    office: 'Kenton County Commissioner, District 1',
    election: alumniCandidatesElection,
    status: 'vs. incumbent Beth Sewell',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2021/01/rsz_sarah_froelich.jpg',
    ),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Sarah_Froelich_(Park_Hills_City_Council_At-large,_Kentucky,_candidate_2024)',
    ),
    donateUrl: Uri.parse(
      'https://secure.actblue.com/donate/sarahforkentoncounty',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-ruth-gao',
    name: 'Ruth Gao',
    classYear: 2024,
    office: 'Jeffersontown City Council, At-large',
    election: alumniCandidatesElection,
    status: 'Incumbent',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2024/01/Ruth-Gao-1_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://www.ruthgao.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Ruth_Gao'),
  ),
  AlumniCandidate(
    seedId: 'emky-yvette-de-la-guardia',
    name: 'Yvette De La Guardia',
    classYear: 2022,
    office: 'Jefferson District Court Judge, Division 4',
    election: alumniCandidatesElection,
    status: 'Unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/01/F7713BE6-FB1B-4E5A-A258-AF26887DA3D4_1_201_a-Yvette-De-La-Guardia_400x400_acf_cropped.jpeg',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Yvette_De_La_Guardia'),
  ),
  AlumniCandidate(
    seedId: 'emky-willow-hambrick',
    name: 'Willow Hambrick',
    classYear: 2019,
    office: 'Georgetown City Council, At-large',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/02/23DC49FB-0B30-429C-A43E-CFECDCB9046B-Willow-Hambrick_400x400_acf_cropped.jpeg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-kesia-hatcher',
    name: 'Kesia Hatcher',
    classYear: 2024,
    office: 'Simpsonville City Commission',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2024/01/Kesia-Hatcher_400x400_acf_cropped.jpg',
    ),
    volunteerOpportunities: [
      VolunteerOpportunity(
        title: 'KFTC phone bank for New Power PAC candidates, incl. Kesia',
        startsAt: DateTime(2026, 10, 22, 18, 0),
        endsAt: DateTime(2026, 10, 22, 20, 0),
        location: 'Virtual on Zoom (Shelby County)',
        signupUrl: Uri.parse('https://www.mobilize.us/kftc/event/1038693/'),
      ),
    ],
  ),
  AlumniCandidate(
    seedId: 'emky-alexandria-hayes',
    name: 'Alexandria Hayes',
    classYear: 2021,
    office: 'Glasgow City Council, At-large',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2021/01/rsz_alex_hayes_400x400_acf_cropped.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-rene-heinrich',
    name: 'Rene Heinrich',
    classYear: 2016,
    office: 'Highland Heights City Council',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/Hein.jpg',
    ),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Rene_Heinrich_(Highland_Heights_City_Council_At-large,_Kentucky,_candidate_2024)',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-tanisha-hickerson',
    name: 'Tanisha Hickerson',
    classYear: 2017,
    office: 'Jefferson District Court Judge, Division 9',
    election: alumniCandidatesElection,
    status: 'Unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/02/TAHheadshot-Tanisha-Hickerson_400x400_acf_cropped.jpg',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Tanisha_Hickerson'),
  ),
  AlumniCandidate(
    seedId: 'emky-deja-jackson',
    name: 'Deja Jackson',
    classYear: 2021,
    office: 'JCPS Board of Education, District 4',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/02/rsz_2deja_jackson_400x400_acf_cropped_400x400_acf_cropped.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-whitney-johns',
    name: 'Whitney Johns',
    classYear: 2023,
    office: 'Circuit Judge, 50th Judicial Circuit, Division 1',
    election: alumniCandidatesElection,
    status: 'vs. Christopher Reed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2023/01/Whitney-Johns_400x400_acf_cropped.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-nima-kulkarni',
    name: 'Nima Kulkarni',
    classYear: 2012,
    office: 'Kentucky House of Representatives, District 40',
    election: alumniCandidatesElection,
    status: 'Incumbent, unopposed in general',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/31337813_199102104206995_3184542001706041344_o_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://www.votenima.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Nima_Kulkarni'),
    donateUrl: Uri.parse(
      'https://actionnetwork.org/fundraising/support-nima-kulkarni-for-state-house-representative',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-shayla-lynch',
    name: 'Shayla D. Lynch',
    classYear: 2017,
    office: 'Lexington-Fayette Urban County Council, District 2',
    election: alumniCandidatesElection,
    status: 'Incumbent, unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/02/Bio-Pic-Shayla-Lynch_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://www.shaylaforlex.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Shayla_Lynch'),
    volunteerUrl: Uri.parse('https://www.shaylaforlex.com/get-involved'),
    donateUrl: Uri.parse(
      'https://secure.anedot.com/2f826878-0af4-41af-8e69-a5265563271d/donate',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-brenda-martin',
    name: 'Bren Martin',
    classYear: 2024,
    office: 'Russell Independent Board of Education',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2024/01/Bren-Martin_400x400_acf_cropped.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-brenda-monarrez',
    name: 'Brenda Monarrez',
    classYear: 2012,
    office: 'Lexington-Fayette Urban County Council, District 4',
    election: alumniCandidatesElection,
    status: 'vs. incumbent Emma Curtis',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/BB_400x400_acf_cropped.png',
    ),
    campaignUrl: Uri.parse('https://www.monarrez4lex.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Brenda_Monarrez'),
    donateUrl: Uri.parse('https://secure.anedot.com/monarrez4lex/donate'),
  ),
  AlumniCandidate(
    seedId: 'emky-jessica-moore',
    name: 'Jessica Moore',
    classYear: 2014,
    office: 'Jefferson District Court Judge, Division 11',
    election: alumniCandidatesElection,
    status: 'Unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/judge_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://judgejessicamoore.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Jessica_Moore'),
    donateUrl: Uri.parse(
      'https://judgejessicamoore.com/wp-content/uploads/2025/10/moore-donate.pdf',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-lianna-nguyen',
    name: 'Lianna Nguyen',
    classYear: 2026,
    office: 'Boone County Commissioner, District 2',
    election: alumniCandidatesElection,
    status: 'vs. John Schickel',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2026/07/Lianna-1-scaled_400x400_acf_cropped.jpeg',
    ),
    campaignUrl: Uri.parse('https://www.lianna4boone.com/'),
    volunteerUrl: Uri.parse('https://www.lianna4boone.com/volunteer'),
    donateUrl: Uri.parse('https://www.lianna4boone.com/contribute'),
  ),
  AlumniCandidate(
    seedId: 'emky-lt-col-terry-owens',
    name: 'Terry Owens',
    classYear: 2018,
    office: 'Mayor of Radcliff',
    election: alumniCandidatesElection,
    status: 'vs. Toshie Murrell',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/Terry_400x400_acf_cropped.jpg',
    ),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Terry_Owens_(Radcliff_City_Council_At-large,_Kentucky,_candidate_2024)',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-shameka-parrish-wright',
    name: 'Shameka Parrish-Wright',
    classYear: 2022,
    office: 'Mayor of Louisville Metro',
    election: alumniCandidatesElection,
    status: 'Advanced from primary; vs. incumbent Craig Greenberg',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/01/SPW-scaled_400x400_acf_cropped.jpg',
    ),
    campaignUrl: Uri.parse('https://shamekaforlouisville.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Shameka_Parrish-Wright'),
    volunteerUrl: Uri.parse(
      'https://docs.google.com/forms/d/e/1FAIpQLSeyRw37BqYCHqe4oTFvqFizLopQ-JrcQzQR1U0dA_gLi64P9g/viewform',
    ),
    donateUrl: Uri.parse(
      'https://secure.actblue.com/donate/shameka-parrish-wright-1',
    ),
    volunteerOpportunities: [
      VolunteerOpportunity(
        title: 'Canvass for Shameka Parrish-Wright',
        startsAt: DateTime(2026, 10, 3, 11, 0),
        endsAt: DateTime(2026, 10, 3, 14, 0),
        location: '735 S Shelby St, Louisville',
        signupUrl: Uri.parse('https://www.mobilize.us/kftc/event/1016220/'),
      ),
    ],
  ),
  AlumniCandidate(
    seedId: 'emky-eryn-pritchett',
    name: 'Eryn Pritchett',
    classYear: 2020,
    office: 'Marshall County Magistrate, District 2',
    election: alumniCandidatesElection,
    status: 'Unopposed',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2020/08/Eryn-Pritchett.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-cherlyn-smith',
    name: 'Cherlyn Smith',
    classYear: 2023,
    office: 'Kentucky House of Representatives, District 25',
    election: alumniCandidatesElection,
    status: 'vs. Steve Bratcher',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2023/01/Cherlyn-Smith_400x400_acf_cropped.jpg',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Cherlyn_Smith'),
  ),
  AlumniCandidate(
    seedId: 'emky-julie-smith-morrow',
    name: 'Julie Smith-Morrow',
    classYear: 2010,
    office: 'Newport City Commission, At-large',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/woo.jpeg',
    ),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Julie_Smith-Morrow_(Newport_City_Commission_At-large,_Kentucky,_candidate_2024)',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-julia-springsteen',
    name: 'Julia Springsteen',
    classYear: 2018,
    office: 'Elizabethtown City Council, At-large',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2022/02/JSpringsteen-Julia-Springsteen_400x400_acf_cropped.jpeg',
    ),
    ballotpediaUrl: Uri.parse(
      'https://ballotpedia.org/Julia_Springsteen_(Elizabethtown_City_Council_At-large,_Kentucky,_candidate_2024)',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-wilanne-stangel',
    name: 'Wilanne Stangel',
    classYear: 2024,
    office: 'Kentucky House of Representatives, District 69',
    election: alumniCandidatesElection,
    status: 'vs. Steven Doan',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2024/01/emerge-photo-Wilanne-Stangel.jpg',
    ),
    campaignUrl: Uri.parse('https://wilannestangel.com/'),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Wilanne_Stangel'),
    donateUrl: Uri.parse('https://secure.actblue.com/donate/wilanne4ky'),
    volunteerOpportunities: [
      VolunteerOpportunity(
        title: 'Day of Action canvass for Wilanne Stangel (HD 69)',
        startsAt: DateTime(2026, 10, 11, 16, 0),
        endsAt: DateTime(2026, 10, 11, 18, 0),
        location: 'Railroad Depot Park, 3313 Crescent Ave, Erlanger',
        signupUrl: Uri.parse('https://www.mobilize.us/kydems/event/1016841/'),
      ),
    ],
  ),
  AlumniCandidate(
    seedId: 'emky-rita-r-thomas',
    name: 'Rita R. Thomas',
    classYear: 2015,
    office: 'Bracken County Magistrate, District 2',
    election: alumniCandidatesElection,
    status: 'vs. Scott Miller',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2018/07/14955937_10101415929348540_829905949380760081_n_400x400_acf_cropped.jpg',
    ),
  ),
  AlumniCandidate(
    seedId: 'emky-leesa-unger',
    name: 'Leesa Unger',
    classYear: 2020,
    office: 'Frankfort City Commission, At-large',
    election: alumniCandidatesElection,
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2020/08/Leesa-1917-ZF-5265-39177-1-001-096.jpg',
    ),
    ballotpediaUrl: Uri.parse('https://ballotpedia.org/Leesa_Unger'),
  ),
  AlumniCandidate(
    seedId: 'emky-renee-wilson',
    name: 'Renee Wilson',
    classYear: 2023,
    office: 'Erlanger City Council, At-large',
    election: alumniCandidatesElection,
    status: 'Incumbent',
    photoUrl: Uri.parse(
      'https://ky.emergeamerica.org/wp-content/uploads/sites/22/2023/01/Renee-Wilson-2.jpg',
    ),
  ),
]);
