#!/usr/bin/env python3
"""Generate lib/features/alumni_running/alumni_candidates.dart.

Source of truth is emerge_ky_seed.json (repo root): only Emerge Kentucky
alumnae whose candidacy_2026.show_on_card is true appear on the Ballot page.
Medium/low-confidence name matches stay off until staff confirm them and flip
show_on_card in the seed.

tool/ballot/ballot_enrichment.json adds verified extras the seed doesn't
carry (photo, Ballotpedia profile, dated volunteer events) and may override
a seed link (set it to null to suppress a broken one).

Usage: python3 tool/ballot/build_ballot.py
"""

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SEED = ROOT / 'emerge_ky_seed.json'
ENRICHMENT = ROOT / 'tool' / 'ballot' / 'ballot_enrichment.json'
OUT = ROOT / 'lib' / 'features' / 'alumni_running' / 'alumni_candidates.dart'

LINK_FIELDS = ('campaign_url', 'volunteer_url', 'donate_url')


def dart_str(value):
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$') + "'"


def dart_uri(value):
    return f'Uri.parse({dart_str(value)})'


def dart_datetime(value):
    # "2026-10-03T10:00": the event's local wall-clock time.
    m = re.fullmatch(r'(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})', value)
    if not m:
        raise SystemExit(f'Bad event time {value!r}; use YYYY-MM-DDTHH:MM')
    return 'DateTime(' + ', '.join(str(int(g)) for g in m.groups()) + ')'


def race(candidacy):
    office = candidacy['office']
    district = (candidacy.get('district') or '').strip()
    if not district:
        return office
    # Seed abbreviates legislative districts ("HD 28", "SD 26").
    district = re.sub(r'^(HD|SD)\s+', 'District ', district)
    return f'{office}, {district}'


def main():
    seed = json.loads(SEED.read_text())
    extras = json.loads(ENRICHMENT.read_text())['candidates']

    rows = []
    for alum in seed['alumni']:
        candidacy = alum.get('candidacy_2026') or {}
        if not candidacy.get('show_on_card') or alum.get('is_deceased'):
            continue
        if candidacy.get('status') != 'on_ballot':
            continue
        rows.append((alum, candidacy, extras.get(alum['seed_id'], {})))

    unknown = set(extras) - {a['seed_id'] for a, _, _ in rows}
    if unknown:
        raise SystemExit(f'Enrichment for alumnae not on the card: {sorted(unknown)}')

    rows.sort(key=lambda r: r[0]['full_name'].split()[-1].lower())

    lines = [
        '// GENERATED by tool/ballot/build_ballot.py — do not edit by hand.',
        '// Edit emerge_ky_seed.json or tool/ballot/ballot_enrichment.json, then',
        '// run `python3 tool/ballot/build_ballot.py`.',
        '',
        "import 'package:npo_community/features/alumni_running/models/alumni_candidate.dart';",
        '',
        "const String alumniCandidatesElection = '2026 General Election · Nov. 3, 2026';",
        '',
        '/// Candidate cards come down once Election Day is over.',
        'final DateTime alumniCandidatesHideAfter = DateTime(2026, 11, 4);',
        '',
        '/// Emerge Kentucky alumnae on the Nov. 3, 2026 ballot',
        f'/// ({len(rows)} confirmed in emerge_ky_seed.json).',
        'final List<AlumniCandidate> alumniCandidates2026 = List.unmodifiable([',
    ]
    for alum, candidacy, extra in rows:
        links = {f: (extra[f] if f in extra else candidacy.get(f)) for f in LINK_FIELDS}
        # An entry with no Uri or DateTime is a compile-time constant; the
        # analyzer insists on `const` for those.
        has_runtime_values = bool(
            extra.get('photo_url') or extra.get('ballotpedia_url')
            or any(links.values()) or extra.get('volunteer_opportunities')
        )
        lines.append('  AlumniCandidate(' if has_runtime_values else '  const AlumniCandidate(')
        lines.append(f"    seedId: {dart_str(alum['seed_id'])},")
        lines.append(f"    name: {dart_str(alum['full_name'])},")
        if alum.get('class_year') is not None:
            lines.append(f"    classYear: {alum['class_year']},")
        lines.append(f'    office: {dart_str(race(candidacy))},')
        lines.append('    election: alumniCandidatesElection,')
        if candidacy.get('status_note'):
            lines.append(f"    status: {dart_str(candidacy['status_note'])},")
        if extra.get('photo_url'):
            lines.append(f"    photoUrl: {dart_uri(extra['photo_url'])},")
        if links['campaign_url']:
            lines.append(f"    campaignUrl: {dart_uri(links['campaign_url'])},")
        if extra.get('ballotpedia_url'):
            lines.append(f"    ballotpediaUrl: {dart_uri(extra['ballotpedia_url'])},")
        if links['volunteer_url']:
            lines.append(f"    volunteerUrl: {dart_uri(links['volunteer_url'])},")
        if links['donate_url']:
            lines.append(f"    donateUrl: {dart_uri(links['donate_url'])},")
        events = extra.get('volunteer_opportunities') or []
        if events:
            lines.append('    volunteerOpportunities: [')
            for e in events:
                lines.append('      VolunteerOpportunity(')
                lines.append(f"        title: {dart_str(e['title'])},")
                lines.append(f"        startsAt: {dart_datetime(e['starts_at'])},")
                if e.get('ends_at'):
                    lines.append(f"        endsAt: {dart_datetime(e['ends_at'])},")
                if e.get('location'):
                    lines.append(f"        location: {dart_str(e['location'])},")
                lines.append(f"        signupUrl: {dart_uri(e['signup_url'])},")
                lines.append('      ),')
            lines.append('    ],')
        lines.append('  ),')
    lines.append(']);')
    OUT.write_text('\n'.join(lines) + '\n')
    # Keep CI's `dart format --set-exit-if-changed` check green.
    subprocess.run(['dart', 'format', str(OUT)], check=True, capture_output=True)
    print(f'wrote {OUT.relative_to(ROOT)}: {len(rows)} candidates')


if __name__ == '__main__':
    main()
