name: transconnect
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.8.1
  provider: ^6.0.3
  http: ^1.5.0
  shared_preferences: ^2.0.7
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  table_calendar: ^3.1.3
  intl: ^0.20.2
  emoji_picker_flutter: ^2.2.0
  timeago: ^3.6.1
  web_socket_channel: ^3.0.0
  logger: ^2.3.0
  adaptive_theme: ^3.6.0
  icalendar_parser: ^2.1.0
  url_launcher: ^6.3.0
  scoped_model: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
