// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZJ4HZt2TsVWPtbtaWNxp1ZSfXhieL6w',
    appId: '1:1063960061005:web:8d2aec6b854d8683736804',
    messagingSenderId: '1063960061005',
    projectId: 'transconnectky',
    authDomain: 'transconnectky.firebaseapp.com',
    storageBucket: 'transconnectky.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZqWnwJY1o8C5xidvvfxRcUZpu6el0CG8',
    appId: '1:1063960061005:android:a13175de547661fc736804',
    messagingSenderId: '1063960061005',
    projectId: 'transconnectky',
    storageBucket: 'transconnectky.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgmyDKAWFNBl63aaySgAB67Ma1ZTrszI',
    appId: '1:1063960061005:ios:fe2b92b8cf988be4736804',
    messagingSenderId: '1063960061005',
    projectId: 'transconnectky',
    storageBucket: 'transconnectky.appspot.com',
    iosBundleId: 'com.example.transconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgmyDKAWFNBl63aaySgAB67Ma1ZTrszI',
    appId: '1:1063960061005:ios:fe2b92b8cf988be4736804',
    messagingSenderId: '1063960061005',
    projectId: 'transconnectky',
    storageBucket: 'transconnectky.appspot.com',
    iosBundleId: 'com.example.transconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuZJ4HZt2TsVWPtbtaWNxp1ZSfXhieL6w',
    appId: '1:1063960061005:web:a7c235ea15a106f6736804',
    messagingSenderId: '1063960061005',
    projectId: 'transconnectky',
    authDomain: 'transconnectky.firebaseapp.com',
    storageBucket: 'transconnectky.appspot.com',
  );
}
